[package]
name = "robot"
version = "0.1.0"
edition = "2021"

[dependencies]
physics = { path = "../physics" }
nalgebra = "0.32"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
rand_distr = "0.4"
